{% set name = "temmeta" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b368a3a92b9f83e15420c35c6650f0e2b5c0fb0a7cd25c776b10d9d9677b7da1

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas
    - numpy
    - matplotlib-base
    - scipy
    - hyperspy
    - matplotlib-scalebar
    - tqdm
    - pillow

test:
  imports:
    - temmeta

about:
  home: https://github.com/din14970/TEMMETA
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE  # license file is available in the next release - therefore the license file in the feedstock can be removed.
  summary: TEMMETA is a library for transmission electron microscopy (TEM) (meta)data manipulation.

  description: |
    TEMMETA is a library for transmission electron microscopy (TEM) 
    (meta)data manipulation. The aim is to offer a one stop place for 
    very basic to intermediate level operations on (S)TEM data, and 
    be a kind of python version of ImageJ + Digital Micrograph + Velox.
  doc_url: https://github.com/din14970/TEMMETA
  dev_url: https://github.com/din14970/TEMMETA

extra:
  recipe-maintainers:
    - jan-janssen
    - din14970
